(() => {
  let model = null;
  let requestToken = null;
  let selectedProfile = null;
  let selectedService = null;
  const $ = (id) => document.getElementById(id);
  const label = { waiting_approval: "等待你的审批", running: "正在处理", requested: "等待 Pi 接手", completed: "已完成", cancelled: "已取消", rejected: "已驳回", failed: "处理失败" };
  const note = (message, error = false) => { $("notice").textContent = message; $("notice").style.color = error ? "#a12b32" : "#066b62"; };
  async function api(path, options = {}) { const configured = { ...options, headers: { ...(options.headers || {}) } }; if ((configured.method || "GET").toUpperCase() !== "GET") configured.headers["X-Director-Token"] = requestToken || ""; const response = await fetch(path, configured); const data = await response.json(); if (!response.ok) throw new Error(data.error || "操作未完成"); return data; }
  function currentProfile() { return model.profiles.find((profile) => profile.id === selectedProfile); }
  function currentService() { return currentProfile()?.services.find((service) => service.id === selectedService); }
  function choice(title, description, selected) { const button = document.createElement("button"); button.className = `choice ${selected ? "selected" : ""}`; const strong = document.createElement("strong"); strong.textContent = title; const small = document.createElement("small"); small.textContent = description; button.append(strong, small); return button; }
  function renderProfiles() { const box = $("profiles"); box.replaceChildren(...model.profiles.map((profile) => { const button = choice(profile.display_name, profile.description, profile.id === selectedProfile); button.onclick = () => { selectedProfile = profile.id; selectedService = profile.default_service; render(); }; return button; })); }
  function renderServices() { const profile = currentProfile(); const box = $("services"); box.replaceChildren(...profile.services.map((service) => { const button = choice(service.display_name, service.description, service.id === selectedService); button.onclick = () => { selectedService = service.id; renderWorkflow(); renderServices(); }; return button; })); }
  function renderWorkflow(task) { const workflowId = task?.workflow_id || currentService()?.workflow; const workflow = model.workflows[workflowId]; const box = $("workflow"); if (!workflow) { box.textContent = "未找到可展示的工作流。"; return; } box.replaceChildren(); const title = document.createElement("p"); title.textContent = workflow.display_name; box.append(title); const flow = document.createElement("div"); flow.className = "flow"; const done = task?.completed_nodes || []; workflow.nodes.forEach((node) => { const item = document.createElement("span"); item.className = `node ${done.includes(node.id) ? "done" : ""} ${(task?.current_node === node.id || task?.waiting_node === node.id) ? "current" : ""} ${node.type === "approval" ? "approval" : ""}`; item.textContent = node.id; item.title = node.type; flow.append(item); }); box.append(flow); }
  function renderTasks() { const box = $("tasks"); box.replaceChildren(); if (!model.tasks.length) { box.textContent = "还没有任务。先选择服务并写下任务说明。"; renderWorkflow(); return; } model.tasks.forEach((task, index) => { const template = $("task-template").content.cloneNode(true); template.querySelector("strong").textContent = `${task.profile_id || ""} / ${task.service_id || ""}`; const badge = template.querySelector(".status"); badge.textContent = label[task.status] || task.status || "未知"; if (Object.hasOwn(label, task.status)) badge.classList.add(task.status); template.querySelector(".task-meta").textContent = `节点：${task.waiting_node || task.current_node || "等待 Pi 接手"} · 版本 ${task.version ?? "-"}`; template.querySelector(".task-request").textContent = task.request || ""; const actions = template.querySelector(".task-actions"); const article = template.querySelector("article"); if (task.pending_write) { const title = document.createElement("p"); title.className = "write-intent-title"; title.textContent = `待写入内容（${task.pending_write.logical_tool} · ${task.pending_write.status}）`; const hash = document.createElement("small"); hash.className = "write-intent-hash"; hash.textContent = `校验码：${task.pending_write.payload_sha256}`; const payload = document.createElement("pre"); payload.className = "write-intent"; try { payload.textContent = JSON.stringify(JSON.parse(task.pending_write.canonical_payload), null, 2); } catch { payload.textContent = task.pending_write.canonical_payload || ""; } article.insertBefore(title, actions); article.insertBefore(hash, actions); article.insertBefore(payload, actions); } if (task.status === "waiting_approval") addAction(actions, task, "approve", "批准"); if (task.status === "waiting_approval") addAction(actions, task, "reject", "驳回"); if (task.status === "waiting_approval") addAction(actions, task, "cancel", "取消任务"); article.onclick = (event) => { if (!event.target.closest("button")) renderWorkflow(task); }; box.append(template); if (index === 0) renderWorkflow(task); }); }
  function addAction(box, task, decision, text) { const button = document.createElement("button"); button.className = `action ${decision}`; button.textContent = text; button.onclick = async () => { const suffix = decision === "approve" && task.pending_write ? `\n\n本次批准将绑定校验码：\n${task.pending_write.payload_sha256}` : ""; if (!confirm(`确认${text}？${suffix}`)) return; const body = {decision, version:task.version}; if (decision === "approve" && task.pending_write) { body.intent_id = task.pending_write.intent_id; body.payload_sha256 = task.pending_write.payload_sha256; } try { const reply = await api(`/api/tasks/${encodeURIComponent(task.task_id)}/decision`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) }); note(reply.message); await load(); } catch (error) { note(error.message, true); await load(); } }; box.append(button); }
  function summaryRow(className, left, right) { const row = document.createElement("div"); row.className = className; const name = document.createElement("span"); name.textContent = left; const detail = document.createElement("span"); detail.textContent = right; row.append(name, detail); return row; }
  function renderData() { const box = $("data-summary"); const all = [...model.data.knowledge, ...model.data.sales]; box.replaceChildren(...all.map((item) => { const detail = item.exists ? `${item.records ?? "?"} 条 · ${item.updated_at || "未知时间"}` : "尚未创建"; return summaryRow("summary-row", item.path.split("/").pop(), detail); })); }
  function renderOutputs() { const box = $("outputs"); box.replaceChildren(); if (!model.outputs.length) { box.textContent = "暂无可显示的产物。"; return; } model.outputs.forEach((item) => box.append(summaryRow("output-row", item.name, item.modified_at))); }
  function render() { renderProfiles(); renderServices(); renderTasks(); renderData(); renderOutputs(); }
  async function load() { model = await api("/api/bootstrap"); requestToken = model.request_token; if (!selectedProfile || !model.profiles.some((item) => item.id === selectedProfile)) { selectedProfile = model.profiles[0]?.id; selectedService = currentProfile()?.default_service; } render(); }
  $("create").onclick = async () => { const request = $("request").value.trim(); if (!request) { note("请先写下任务说明。", true); return; } try { const response = await api("/api/task-requests", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({profile_id:selectedProfile, service_id:selectedService, request})}); $("request").value = ""; note(`任务已登记（${response.request_id}），等待 Pi 工作流接手。`); } catch (error) { note(error.message, true); } };
  load().catch((error) => note(`无法读取工作台：${error.message}`, true));
  setInterval(() => load().catch(() => {}), 5000);
})();
